import type { Metadata } from "next";
import "./globals.css";

import { Roboto } from "next/font/google";

// Emotion cache provider (client-side only)
import Providers from "./providers";

const roboto = Roboto({
    weight: ["300", "400", "500", "700"],
    subsets: ["latin"],
    display: "swap",
    variable: "--font-roboto",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={roboto.variable}>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
